[2022-09-19T07:01:16.344+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: pg_extract.pg_extract_task scheduled__2022-09-18T07:01:12.626380+00:00 [queued]>
[2022-09-19T07:01:16.483+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: pg_extract.pg_extract_task scheduled__2022-09-18T07:01:12.626380+00:00 [queued]>
[2022-09-19T07:01:16.488+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2022-09-19T07:01:16.500+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 1
[2022-09-19T07:01:16.520+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2022-09-19T07:01:16.616+0000] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): pg_extract_task> on 2022-09-18 07:01:12.626380+00:00
[2022-09-19T07:01:16.659+0000] {standard_task_runner.py:52} INFO - Started process 343 to run task
[2022-09-19T07:01:16.675+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'pg_extract', 'pg_extract_task', 'scheduled__2022-09-18T07:01:12.626380+00:00', '--job-id', '125', '--raw', '--subdir', 'DAGS_FOLDER/x_dag.py', '--cfg-path', '/tmp/tmps9u57a8q', '--error-file', '/tmp/tmpc9k45eae']
[2022-09-19T07:01:16.697+0000] {standard_task_runner.py:80} INFO - Job 125: Subtask pg_extract_task
[2022-09-19T07:01:17.203+0000] {task_command.py:371} INFO - Running <TaskInstance: pg_extract.pg_extract_task scheduled__2022-09-18T07:01:12.626380+00:00 [running]> on host 0d275337f52b
[2022-09-19T07:01:17.724+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=pg_extract
AIRFLOW_CTX_TASK_ID=pg_extract_task
AIRFLOW_CTX_EXECUTION_DATE=2022-09-18T07:01:12.626380+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-18T07:01:12.626380+00:00
[2022-09-19T07:01:17.786+0000] {base.py:68} INFO - Using connection ID 'home' for task execution.
[2022-09-19T07:01:18.856+0000] {x_dag.py:15} INFO - Exporting query to file
[2022-09-19T07:01:18.858+0000] {postgres.py:127} INFO - Running copy expert: COPY (SELECT * FROM CUSTOMER WHERE first_name='john') TO STDOUT WITH CSV HEADER, filename: /home/user/***/customer.csv
[2022-09-19T07:01:18.865+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/x_dag.py", line 16, in pg_extract
    pg_hook.copy_expert(copy_sql, filename='/home/user/airflow/customer.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 129, in copy_expert
    with open(filename, 'w'):
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/airflow/customer.csv'
[2022-09-19T07:01:18.885+0000] {taskinstance.py:1412} INFO - Marking task as FAILED. dag_id=pg_extract, task_id=pg_extract_task, execution_date=20220918T070112, start_date=20220919T070116, end_date=20220919T070118
[2022-09-19T07:01:18.929+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 125 for task pg_extract_task ([Errno 2] No such file or directory: '/home/user/airflow/customer.csv'; 343)
[2022-09-19T07:01:18.995+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-09-19T07:01:19.124+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
