[2022-09-12T10:46:20.537+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: pg_extract.pg_extract_task scheduled__2022-09-11T10:46:14.539911+00:00 [queued]>
[2022-09-12T10:46:20.570+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: pg_extract.pg_extract_task scheduled__2022-09-11T10:46:14.539911+00:00 [queued]>
[2022-09-12T10:46:20.571+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2022-09-12T10:46:20.574+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 1
[2022-09-12T10:46:20.575+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2022-09-12T10:46:20.637+0000] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): pg_extract_task> on 2022-09-11 10:46:14.539911+00:00
[2022-09-12T10:46:20.687+0000] {standard_task_runner.py:52} INFO - Started process 227 to run task
[2022-09-12T10:46:20.714+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'pg_extract', 'pg_extract_task', 'scheduled__2022-09-11T10:46:14.539911+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/x_dag.py', '--cfg-path', '/tmp/tmpckza1lov', '--error-file', '/tmp/tmpr_0373mc']
[2022-09-12T10:46:20.742+0000] {standard_task_runner.py:80} INFO - Job 50: Subtask pg_extract_task
[2022-09-12T10:46:21.097+0000] {task_command.py:371} INFO - Running <TaskInstance: pg_extract.pg_extract_task scheduled__2022-09-11T10:46:14.539911+00:00 [running]> on host 0edf5f972c6d
[2022-09-12T10:46:22.038+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=pg_extract
AIRFLOW_CTX_TASK_ID=pg_extract_task
AIRFLOW_CTX_EXECUTION_DATE=2022-09-11T10:46:14.539911+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-11T10:46:14.539911+00:00
[2022-09-12T10:46:22.157+0000] {base.py:68} INFO - Using connection ID 'home' for task execution.
[2022-09-12T10:46:26.271+0000] {x_dag.py:15} INFO - Exporting query to file
[2022-09-12T10:46:26.274+0000] {postgres.py:127} INFO - Running copy expert: COPY (SELECT * FROM CUSTOMER WHERE first_name='john') TO STDOUT WITH CSV HEADER, filename: /home/user/***/customer.csv
[2022-09-12T10:46:26.282+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/x_dag.py", line 16, in pg_extract
    pg_hook.copy_expert(copy_sql, filename='/home/user/airflow/customer.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 129, in copy_expert
    with open(filename, 'w'):
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/airflow/customer.csv'
[2022-09-12T10:46:26.321+0000] {taskinstance.py:1412} INFO - Marking task as FAILED. dag_id=pg_extract, task_id=pg_extract_task, execution_date=20220911T104614, start_date=20220912T104620, end_date=20220912T104626
[2022-09-12T10:46:26.477+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 50 for task pg_extract_task ([Errno 2] No such file or directory: '/home/user/airflow/customer.csv'; 227)
[2022-09-12T10:46:26.580+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-09-12T10:46:26.768+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
