[2022-09-08T11:32:49.848+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: pg_extract.pg_extract_task manual__2022-09-08T11:32:47.810355+00:00 [queued]>
[2022-09-08T11:32:49.865+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: pg_extract.pg_extract_task manual__2022-09-08T11:32:47.810355+00:00 [queued]>
[2022-09-08T11:32:49.867+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2022-09-08T11:32:49.868+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 1
[2022-09-08T11:32:49.869+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2022-09-08T11:32:49.897+0000] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): pg_extract_task> on 2022-09-08 11:32:47.810355+00:00
[2022-09-08T11:32:49.909+0000] {standard_task_runner.py:52} INFO - Started process 18954 to run task
[2022-09-08T11:32:49.915+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'pg_extract', 'pg_extract_task', 'manual__2022-09-08T11:32:47.810355+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/x_dag.py', '--cfg-path', '/tmp/tmpbd66n569', '--error-file', '/tmp/tmp88gdhf40']
[2022-09-08T11:32:49.919+0000] {standard_task_runner.py:80} INFO - Job 35: Subtask pg_extract_task
[2022-09-08T11:32:50.032+0000] {task_command.py:371} INFO - Running <TaskInstance: pg_extract.pg_extract_task manual__2022-09-08T11:32:47.810355+00:00 [running]> on host 0edf5f972c6d
[2022-09-08T11:32:50.146+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=pg_extract
AIRFLOW_CTX_TASK_ID=pg_extract_task
AIRFLOW_CTX_EXECUTION_DATE=2022-09-08T11:32:47.810355+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-08T11:32:47.810355+00:00
[2022-09-08T11:32:50.163+0000] {base.py:68} INFO - Using connection ID 'vecap_source' for task execution.
[2022-09-08T11:32:50.714+0000] {x_dag.py:15} INFO - Exporting query to file
[2022-09-08T11:32:50.716+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/x_dag.py", line 16, in pg_extract
    pg_hook.copy_expert(copy_sql, filename='/home/user/airflow/customer.csv')
AttributeError: 'RedshiftSQLHook' object has no attribute 'copy_expert'
[2022-09-08T11:32:50.741+0000] {taskinstance.py:1412} INFO - Marking task as FAILED. dag_id=pg_extract, task_id=pg_extract_task, execution_date=20220908T113247, start_date=20220908T113249, end_date=20220908T113250
[2022-09-08T11:32:50.780+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 35 for task pg_extract_task ('RedshiftSQLHook' object has no attribute 'copy_expert'; 18954)
[2022-09-08T11:32:50.825+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-09-08T11:32:50.898+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
