[2022-10-08T18:17:13.480+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: pg_extract.pg_extract_task scheduled__2022-10-07T12:36:42.982207+00:00 [queued]>
[2022-10-08T18:17:13.584+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: pg_extract.pg_extract_task scheduled__2022-10-07T12:36:42.982207+00:00 [queued]>
[2022-10-08T18:17:13.586+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2022-10-08T18:17:13.589+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 1
[2022-10-08T18:17:13.595+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2022-10-08T18:17:13.710+0000] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): pg_extract_task> on 2022-10-07 12:36:42.982207+00:00
[2022-10-08T18:17:13.746+0000] {standard_task_runner.py:52} INFO - Started process 49970 to run task
[2022-10-08T18:17:13.775+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'pg_extract', 'pg_extract_task', 'scheduled__2022-10-07T12:36:42.982207+00:00', '--job-id', '248', '--raw', '--subdir', 'DAGS_FOLDER/x_dag.py', '--cfg-path', '/tmp/tmpon2f0d62', '--error-file', '/tmp/tmpz22g5_pf']
[2022-10-08T18:17:13.785+0000] {standard_task_runner.py:80} INFO - Job 248: Subtask pg_extract_task
[2022-10-08T18:17:15.064+0000] {task_command.py:371} INFO - Running <TaskInstance: pg_extract.pg_extract_task scheduled__2022-10-07T12:36:42.982207+00:00 [running]> on host a41ad1c55a2c
[2022-10-08T18:17:15.273+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=pg_extract
AIRFLOW_CTX_TASK_ID=pg_extract_task
AIRFLOW_CTX_EXECUTION_DATE=2022-10-07T12:36:42.982207+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-07T12:36:42.982207+00:00
[2022-10-08T18:17:15.295+0000] {base.py:68} INFO - Using connection ID 'home' for task execution.
[2022-10-08T18:17:16.037+0000] {x_dag.py:13} INFO - Exporting query to file
[2022-10-08T18:17:16.071+0000] {postgres.py:127} INFO - Running copy expert: COPY (SELECT * FROM CUSTOMER WHERE first_name='john') TO STDOUT WITH CSV HEADER, filename: /home/user/***/customer.csv
[2022-10-08T18:17:16.082+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/x_dag.py", line 14, in pg_extract
    pg_hook.copy_expert(copy_sql, filename='/home/user/airflow/customer.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 129, in copy_expert
    with open(filename, 'w'):
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/airflow/customer.csv'
[2022-10-08T18:17:16.146+0000] {taskinstance.py:1412} INFO - Marking task as FAILED. dag_id=pg_extract, task_id=pg_extract_task, execution_date=20221007T123642, start_date=20221008T181713, end_date=20221008T181716
[2022-10-08T18:17:16.220+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 248 for task pg_extract_task ([Errno 2] No such file or directory: '/home/user/airflow/customer.csv'; 49970)
[2022-10-08T18:17:16.294+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-10-08T18:17:16.443+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
