[2022-09-28T02:25:36.074+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: pg_extract.pg_extract_task scheduled__2022-09-26T14:21:30.391338+00:00 [queued]>
[2022-09-28T02:25:36.304+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: pg_extract.pg_extract_task scheduled__2022-09-26T14:21:30.391338+00:00 [queued]>
[2022-09-28T02:25:36.309+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2022-09-28T02:25:36.317+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 1
[2022-09-28T02:25:36.325+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2022-09-28T02:25:36.602+0000] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): pg_extract_task> on 2022-09-26 14:21:30.391338+00:00
[2022-09-28T02:25:36.671+0000] {standard_task_runner.py:52} INFO - Started process 17961 to run task
[2022-09-28T02:25:36.830+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'pg_extract', 'pg_extract_task', 'scheduled__2022-09-26T14:21:30.391338+00:00', '--job-id', '154', '--raw', '--subdir', 'DAGS_FOLDER/x_dag.py', '--cfg-path', '/tmp/tmpmls94u_l', '--error-file', '/tmp/tmp0pqz1b45']
[2022-09-28T02:25:36.875+0000] {standard_task_runner.py:80} INFO - Job 154: Subtask pg_extract_task
[2022-09-28T02:25:38.157+0000] {task_command.py:371} INFO - Running <TaskInstance: pg_extract.pg_extract_task scheduled__2022-09-26T14:21:30.391338+00:00 [running]> on host a41ad1c55a2c
[2022-09-28T02:25:45.652+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=pg_extract
AIRFLOW_CTX_TASK_ID=pg_extract_task
AIRFLOW_CTX_EXECUTION_DATE=2022-09-26T14:21:30.391338+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-26T14:21:30.391338+00:00
[2022-09-28T02:25:45.815+0000] {base.py:68} INFO - Using connection ID 'home' for task execution.
[2022-09-28T04:37:10.877+0000] {x_dag.py:15} INFO - Exporting query to file
[2022-09-28T04:37:10.912+0000] {postgres.py:127} INFO - Running copy expert: COPY (SELECT * FROM CUSTOMER WHERE first_name='john') TO STDOUT WITH CSV HEADER, filename: /home/user/***/customer.csv
[2022-09-28T04:37:10.918+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/x_dag.py", line 16, in pg_extract
    pg_hook.copy_expert(copy_sql, filename='/home/user/airflow/customer.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 129, in copy_expert
    with open(filename, 'w'):
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/airflow/customer.csv'
[2022-09-28T04:37:11.077+0000] {taskinstance.py:1412} INFO - Marking task as FAILED. dag_id=pg_extract, task_id=pg_extract_task, execution_date=20220926T142130, start_date=20220928T022536, end_date=20220928T043711
[2022-09-28T04:37:11.418+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 154 for task pg_extract_task ([Errno 2] No such file or directory: '/home/user/airflow/customer.csv'; 17961)
[2022-09-28T04:37:12.003+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-09-28T04:37:12.428+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
