[2022-09-19T07:01:09.205+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: pg_extract.pg_extract_task scheduled__2022-09-16T10:46:21.254200+00:00 [queued]>
[2022-09-19T07:01:09.254+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: pg_extract.pg_extract_task scheduled__2022-09-16T10:46:21.254200+00:00 [queued]>
[2022-09-19T07:01:09.257+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2022-09-19T07:01:09.258+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 1
[2022-09-19T07:01:09.259+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2022-09-19T07:01:09.326+0000] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): pg_extract_task> on 2022-09-16 10:46:21.254200+00:00
[2022-09-19T07:01:09.343+0000] {standard_task_runner.py:52} INFO - Started process 209 to run task
[2022-09-19T07:01:09.360+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'pg_extract', 'pg_extract_task', 'scheduled__2022-09-16T10:46:21.254200+00:00', '--job-id', '121', '--raw', '--subdir', 'DAGS_FOLDER/x_dag.py', '--cfg-path', '/tmp/tmpppooji4o', '--error-file', '/tmp/tmpiis3etmi']
[2022-09-19T07:01:09.368+0000] {standard_task_runner.py:80} INFO - Job 121: Subtask pg_extract_task
[2022-09-19T07:01:09.732+0000] {task_command.py:371} INFO - Running <TaskInstance: pg_extract.pg_extract_task scheduled__2022-09-16T10:46:21.254200+00:00 [running]> on host 0d275337f52b
[2022-09-19T07:01:10.329+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=pg_extract
AIRFLOW_CTX_TASK_ID=pg_extract_task
AIRFLOW_CTX_EXECUTION_DATE=2022-09-16T10:46:21.254200+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-16T10:46:21.254200+00:00
[2022-09-19T07:01:10.380+0000] {base.py:68} INFO - Using connection ID 'home' for task execution.
[2022-09-19T07:01:12.172+0000] {x_dag.py:15} INFO - Exporting query to file
[2022-09-19T07:01:12.189+0000] {postgres.py:127} INFO - Running copy expert: COPY (SELECT * FROM CUSTOMER WHERE first_name='john') TO STDOUT WITH CSV HEADER, filename: /home/user/***/customer.csv
[2022-09-19T07:01:12.196+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/x_dag.py", line 16, in pg_extract
    pg_hook.copy_expert(copy_sql, filename='/home/user/airflow/customer.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 129, in copy_expert
    with open(filename, 'w'):
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/airflow/customer.csv'
[2022-09-19T07:01:12.254+0000] {taskinstance.py:1412} INFO - Marking task as FAILED. dag_id=pg_extract, task_id=pg_extract_task, execution_date=20220916T104621, start_date=20220919T070109, end_date=20220919T070112
[2022-09-19T07:01:12.313+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 121 for task pg_extract_task ([Errno 2] No such file or directory: '/home/user/airflow/customer.csv'; 209)
[2022-09-19T07:01:12.352+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-09-19T07:01:12.545+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
